services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/redis:/data
#    environment:
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
#      - REDIS_USER=${REDIS_USER}
#      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
